index_col: 'flat_id'
target_col: 'log1p_target'
one_hot_drop: 'if_binary'
n_splits: 5
metrics: 
  neg_mae: 'neg_mae'
  neg_rmse: 'neg_rmse'
  neg_mape: 'neg_mape'
  r2: 'r2'
n_jobs: -1 
verbose_catboost: False
random_state_catboost: 42
random_state_kfold: 42
ndigits: 3